### ISSUE TITLE
Uncaught Timeout Error exception

### ISSUE THREAD

**Issue by schmupu** [Apollon77/shelly-iot#12]
Following error occurs in ioBroker:

```
2019-07-17 00:07:04.975 - error: { Error: No reply in 247s
2019-07-17 00:07:04.976 - error: at Timeout._onTimeout (/opt/iobroker/node_modules/coap/lib/retry_send.js:74:16)
2019-07-17 00:07:04.976 - error: at ontimeout (timers.js:498:11)
2019-07-17 00:07:04.976 - error: at tryOnTimeout (timers.js:323:5)
2019-07-17 00:07:04.976 - error: at Timer.listOnTimeout (timers.js:290:5) retransmitTimeout: 247 }
```
I found following solution to avoid the error. Do you think that helps to implement in shelly-iot ?

https://github.com/mcollina/node-coap/issues/114
https://github.com/mcollina/node-coap/issues?utf8=%E2%9C%93&q=is%3Aissue+247

**Comment by Apollon77** [comment]
Could you provide a PR for it and experiment to find best values?
